apiVersion: v1
data:
  middlewares.yaml: |
    http:
      middlewares:
        soveren:
          replicate:
            topic: events
            heartbeattopic: heartbeat
            workerpoolsize: 10
            brokers:
              - kafka:9092
kind: ConfigMap
metadata:
  labels:
    app: traefik-proxy
  name: middlewares
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: detection-tool
  name: detection-tool
spec:
  ports:
  - name: detection-tcp
    port: 8000
    targetPort: 8000
  selector:
    app: detection-tool
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: digger
  name: digger
spec:
  ports:
  - name: digger-tcp
    port: 9000
    targetPort: 9000
  - name: digger-metrics
    port: 9090
    targetPort: 9090
  selector:
    app: digger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  clusterIP: None
  ports:
  - name: kafka-tcp
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik-proxy
  name: traefik-proxy
spec:
  ports:
  - name: traefik-proxy
    port: 8090
    targetPort: 8090
  selector:
    app: traefik-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: detection-tool
  name: detection-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detection-tool
  template:
    metadata:
      labels:
        app: detection-tool
    spec:
      containers:
      - image: soveren/detection-tool:v0.9.1
        imagePullPolicy: IfNotPresent
        name: detection-tool
        ports:
        - containerPort: 8000
          name: detection-tcp
        readinessProbe:
          tcpSocket:
            port: 8000
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 1024Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digger
  name: digger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digger
  template:
    metadata:
      labels:
        app: digger
    spec:
      containers:
      - env:
        - name: SVRN_DIGGER_STATSCLIENT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: soveren-proxy-token
        - name: SVRN_DIGGER_STATSCLIENT_CLIENT_ADDRESS
          value: stats.soveren.io:443
        - name: SVRN_DIGGER_STATSCLIENT_CLIENT_TIMEOUT
          value: 10s
        - name: SVRN_DIGGER_STATSCLIENT_CLIENT_USETLS
          value: "true"
        - name: SVRN_DIGGER_STATSCLIENT_CLIENT_INSECURE
          value: "false"
        - name: SVRN_DIGGER_STOPTIMEOUT
          value: 60s
        - name: SVRN_DIGGER_LOG_FORMATTER
          value: text
        - name: SVRN_DIGGER_DETECTIONTOOL_URI
          value: http://detection-tool:8000
        - name: SVRN_DIGGER_KAFKA_BROKERS
          value: kafka:9092
        - name: SVRN_DIGGER_KAFKA_CONSUMER_GROUP
          value: worker_1
        - name: SVRN_DIGGER_KAFKA_CONSUMER_HANDLERNAME
          value: worker_1
        - name: SVRN_DIGGER_KAFKA_CONSUMER_TOPIC
          value: events
        - name: SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_GROUP
          value: worker_2
        - name: SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_HANDLERNAME
          value: worker_2
        - name: SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_TOPIC
          value: heartbeat
        - name: SVRN_DIGGER_KAFKA_RESENDSLEEP
          value: 1s
        - name: SVRN_DIGGER_INSTRUMENTATION_SERVER_LISTENADDRESS
          value: 0.0.0.0:9000
        - name: SVRN_DIGGER_INSTRUMENTATION_TRACING_AGENTENDPOINT
          value: ""
        - name: SVRN_DIGGER_INSTRUMENTATION_TRACING_COLLECTORENDPOINT
          value: ""
        - name: SVRN_DIGGER_INSTRUMENTATION_TRACING_PROBABILITYRATE
          value: "0"
        image: soveren/digger:v0.9.4
        imagePullPolicy: IfNotPresent
        name: digger
        ports:
        - containerPort: 9000
          name: digger
        - containerPort: 9090
          name: digger-metrics
        readinessProbe:
          tcpSocket:
            port: 9000
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
      initContainers:
      - args:
        - -c
        - for attempt in {1..60}; do sleep 2; nc -zvw5 kafka 9092 && break; done
        image: bash:5.1.4
        name: check-kafka-ready
      - args:
        - -c
        - for attempt in {1..60}; do sleep 2; nc -zvw5 detection-tool 8000 && break;
          done
        image: bash:5.1.4
        name: check-detection-ready
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - args:
        - --override
        - advertised.listeners=PLAINTEXT://$(MY_POD_IP):9092
        - --override
        - log.retention.hours=1
        - --override
        - log.retention.bytes=268435456
        - --override
        - auto.create.topics.enable=false
        env:
        - name: KAFKA_CREATE_TOPICS
          value: heartbeat:1:1,events:10:1
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: soveren/kafka:kraft
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -ce
              - kill -s TERM 1; while $(kill -0 1 2>/dev/null); do sleep 1; done
        name: kafka
        ports:
        - containerPort: 9092
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik-proxy
  name: traefik-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik-proxy
  template:
    metadata:
      labels:
        app: traefik-proxy
    spec:
      containers:
      - env:
        - name: TRAEFIK_LOG_LEVEL
          value: INFO
        - name: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
          value: :8090
        - name: TRAEFIK_PROVIDERS_FILE_DIRECTORY
          value: /etc/traefik/conf/conf.d/
        image: soveren/gateway:v2.6.0-svrn0.9.1
        imagePullPolicy: IfNotPresent
        name: traefik-proxy
        ports:
        - containerPort: 8090
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          tcpSocket:
            port: 8090
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/traefik/conf/conf.d/
          name: replicator
        - mountPath: /etc/traefik/conf/conf.d/middlewares/
          name: middlewares
      initContainers:
      - args:
        - -c
        - for attempt in {1..60}; do sleep 2; nc -zvw5 kafka 9092 && break; done
        image: bash:5.1.4
        name: check-kafka-ready
      restartPolicy: Always
      volumes:
      - configMap:
          name: middlewares
        name: middlewares
      - configMap:
          name: replicator
        name: replicator
