apiVersion: v1
kind: ConfigMap
metadata:
  name: soveren-replicator
  labels:
    stack: soveren
    app: traefik-proxy
data:
  replicator.yaml: |
    http:
      routers:
        defaults:
          entryPoints:
            - web
          rule: PathPrefix(`/`)
          middlewares:
            - soveren
          service: upstream
      services:
        upstream:
          loadBalancer:
            servers:
              - url: http://host:80/
