---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: digger
  name: soveren-digger
spec:
  ports:
    - name: "digger-tcp"
      port: 9000
    - name: "digger-metrics"
      port: 9090
  selector:
    app: digger

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digger
  name: soveren-digger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digger
  template:
    metadata:
      labels:
        app: digger
    spec:
      serviceAccountName: soveren-digger
      initContainers:
        - name: check-kafka-ready
          image: bash:5.1.4
          args: [ '-c', 'for attempt in {1..60}; do sleep 2; nc -zvw5 soveren-kafka 9092 && break; done' ]
        - name: check-detection-ready
          image: bash:5.1.4
          args: [ '-c', 'for attempt in {1..60}; do sleep 2; nc -zvw5 soveren-detection-tool 8000 && break; done' ]
      containers:
        - image: soveren/digger:latest
          name: digger
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 3
          ports:
            - name: "digger"
              containerPort: 9000
            - name: "digger-metrics"
              containerPort: 9090
          env:
            - name: "SVRN_DIGGER_STATSCLIENT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: soveren-token
                  key: token
            - name: "SVRN_DIGGER_STATSCLIENT_CLIENT_ADDRESS"
              value: "stats.soveren.io:443"
            - name: "SVRN_DIGGER_STATSCLIENT_CLIENT_TIMEOUT"
              value: "10s"
            - name: "SVRN_DIGGER_STATSCLIENT_CLIENT_USETLS"
              value: "true"
            - name: "SVRN_DIGGER_STATSCLIENT_CLIENT_INSECURE"
              value: "false"
            - name: "SVRN_DIGGER_STOPTIMEOUT"
              value: "60s"
            - name: "SVRN_DIGGER_LOG_FORMATTER"
              value: "text"
            - name: "SVRN_DIGGER_DETECTIONTOOL_URI"
              value: "http://soveren-detection-tool:8000"
            - name: "SVRN_DIGGER_KAFKA_BROKERS"
              value: "soveren-kafka:9092"
            - name: "SVRN_DIGGER_KAFKA_CONSUMER_GROUP"
              value: "worker_1"
            - name: "SVRN_DIGGER_KAFKA_CONSUMER_HANDLERNAME"
              value: "worker_1"
            - name: "SVRN_DIGGER_KAFKA_CONSUMER_TOPIC"
              value: "events"
            - name: "SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_GROUP"
              value: "worker_2"
            - name: "SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_HANDLERNAME"
              value: "worker_2"
            - name: "SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_TOPIC"
              value: "heartbeat"
            - name: "SVRN_DIGGER_KAFKA_RESENDSLEEP"
              value: "1s"
            - name: "SVRN_DIGGER_INSTRUMENTATION_SERVER_LISTENADDRESS"
              value: "0.0.0.0:9000"
            - name: "SVRN_DIGGER_INSTRUMENTATION_TRACING_AGENTENDPOINT"
              value: ""
            - name: "SVRN_DIGGER_INSTRUMENTATION_TRACING_COLLECTORENDPOINT"
              value: ""
            - name: "SVRN_DIGGER_INSTRUMENTATION_TRACING_PROBABILITYRATE"
              value: "0"
            - name: SVRN_DIGGER_RESOLVER_KUBERNETES_ENABLED
              value: "true"
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "256Mi"
      restartPolicy: Always
