---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: soveren-interceptor

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: soveren-pods-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: soveren-interceptor-pods-reader
subjects:
  - kind: ServiceAccount
    name: soveren-interceptor
roleRef:
  kind: ClusterRole
  name: soveren-pods-reader
  apiGroup: rbac.authorization.k8s.io
