---
apiVersion: v1
kind: Service
metadata:
  labels:
    stack: soveren
    app: kafka
  name: soveren-kafka
spec:
  clusterIP: None
  ports:
    - name: "kafka-tcp"
      port: 9092
  selector:
    stack: soveren
    app: kafka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    stack: soveren
    app: kafka
  name: soveren-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: soveren
      app: kafka
  template:
    metadata:
      labels:
        stack: soveren
        app: kafka
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: kafka
          image: soveren/kafka:kraft
          args:
            - "--override"
            - "advertised.listeners=PLAINTEXT://$(MY_POD_IP):9092"
            - "--override"
            - "log.retention.hours=1"
            - "--override"
            - "log.retention.bytes=268435456"
            - "--override"
            - "auto.create.topics.enable=false"
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-ce", "kill -s TERM 1; while $(kill -0 1 2>/dev/null); do sleep 1; done" ]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              memory: "1024Mi"
          env:
            - name: "KAFKA_CREATE_TOPICS"
              value: "heartbeat:1:1,events:10:1"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
