---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  stack: soveren

namespace: soveren-interceptor

resources:
- namespace.yaml
- interceptor-sa-cr-crb.yaml
- interceptor.yaml
- kafka-deployment.yaml
- detection-tool.yaml
- digger-deployment.yaml
- digger-sa-crb.yaml

images:
- name: soveren/interceptor
  newTag: v0.13.2
- name: soveren/digger
  newTag: v0.13.2
- name: soveren/detection-tool
  newTag: v0.15.10
