global:
  scrape_interval: 15s
remote_write:
- name: crawler
  url: http://crawler:9100/metrics/send
scrape_configs:
- job_name: prometheus-agent
  static_configs:
  - targets:
    - localhost:9090
- job_name: crawler
  static_configs:
  - targets:
    - crawler:9000
- job_name: detection-tool
  static_configs:
  - targets:
    - detection-tool:9100
- job_name: kafka
  static_configs:
  - targets:
      - kafka-exporter:9100