services:
  digger:
    depends_on:
      kafka:
        condition: service_healthy
      presidio-analyzer:
        condition: service_healthy
    environment:
      SVRN_DIGGER_STATSCLIENT_CLIENT_ADDRESS: stats.soveren.io:443
      SVRN_DIGGER_STATSCLIENT_CLIENT_TIMEOUT: 60s
      SVRN_DIGGER_STATSCLIENT_CLIENT_USETLS: "true"
      SVRN_DIGGER_STATSCLIENT_TOKEN: ''
    expose:
    - '9000'
    healthcheck:
      interval: 5s
      test: bash -c '</dev/tcp/localhost/9000' 2>/dev/null
    image: soveren/digger:v0.3.1
    volumes:
    - /home/runner/work/boxy/boxy/compose/configs/digger_config.yaml:/etc/config.yaml:rw
  kafka:
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    expose:
    - '9092'
    healthcheck:
      interval: 5s
      test: bash -c '</dev/tcp/localhost/9092' 2>/dev/null
    image: bitnami/kafka:2
    volumes:
    - kafka_data:/bitnami:rw
  presidio-analyzer:
    expose:
    - '8000'
    healthcheck:
      interval: 5s
      test: bash -c '</dev/tcp/localhost/8000' 2>/dev/null
    image: soveren/detection-tool:v0.2.0
  traefik:
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: :8090
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: /etc/traefik/conf/conf.d/
    healthcheck:
      interval: 5s
      test: nc -w 1 -z localhost 8090
    image: soveren/gateway:v0.3.0
    ports:
    - published: 8090
      target: 8090
    volumes:
    - /home/runner/work/boxy/boxy/compose/configs/traefik_configs:/etc/traefik/conf:rw
  zookeeper:
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    expose:
    - '2181'
    healthcheck:
      interval: 5s
      test: nc -w 1 -z localhost 2181
    image: bitnami/zookeeper:3.7
    volumes:
    - zookeeper_data:/bitnami:rw
version: '3'
volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local

